/**
 * Skyscraper API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package herokuapp.autocomparator.zsolt.skyscraper.model;

import android.arch.persistence.room.ColumnInfo;

import java.util.ArrayList;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "")
public class CarDetails extends ArrayList<CarDetail> {

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarDetails carDetails = (CarDetails) o;
    return true;
  }

  @Override
  public int hashCode() {
    int result = 17;
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarDetails {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
